name: Build Lichess APK
on:
  workflow_dispatch: # Allows you to trigger the build manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: 'pubspec.yaml'
          
      - name: Fetch Dependencies
        run: flutter pub get
        
      - name: Generate Code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Generate Dummy Signing Key
        run: |
          keytool -genkeypair -v -keystore android/key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias upload -dname "CN=test" -storepass password -keypass password
          echo "storePassword=password" > android/key.properties
          echo "keyPassword=password" >> android/key.properties
          echo "keyAlias=upload" >> android/key.properties
          echo "storeFile=${{ github.workspace }}/android/key.jks" >> android/key.properties
        
      - name: Build APK
        run: flutter build apk --release
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: lichess-neo-apk
          path: build/app/outputs/flutter-apk/app-release.apk
